### ISSUE TITLE
Blazor 0.5.0

### ISSUE THREAD

**Issue by jens-ribbholm** [torhovland/blazor-redux#10]
There seems to be a compile time issue if upgrading Blazor to version 0.5.0 if using blazor-redux. I have tried both upgrading my existing project and referencing blazor-redux in a new example project with Blazor 0.5.0 (that run before referencing).

`Error	MSB3073	The command "dotnet "C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.0\targets\../tools/illink/illink.dll" -l none -c link -u link -b true -t --verbose  -d "C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.0\targets\../tools/mono/bcl/" -d "C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.0\targets\../tools/mono/bcl/Facades/" -o "c:\users\wroom\Source\WebApplication2\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.0\targets\BuiltInBclLinkerDescriptor.xml" -x "c:\users\wroom\Source\WebApplication2\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\wroom\.nuget\packages\blazor-redux\0.0.5\lib\netstandard2.0\BlazorRedux.dll" -a "C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor\0.5.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.5.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.dependencyinjection\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.dependencyinjection.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\wroom\.nuget\packages\microsoft.jsinterop\0.5.0\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\wroom\.nuget\packages\mono.webassembly.interop\0.5.0\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "c:\users\wroom\Source\WebApplication2\obj\Debug\netstandard2.0\WebApplication2.dll"" exited with code 1.	WebApplication2	C:\Users\wroom\.nuget\packages\microsoft.aspnetcore.blazor.build\0.5.0\targets\Blazor.MonoRuntime.targets	441`

**Comment by ransagy** [comment]
The JS Interop part changed in syntax completely and was (obviously) not made backwards compatible, so Blazor-Redux will be needed to be upgraded as well to work on 0.5.x onwards.

**Comment by dog2god** [comment]
I'm having the exact same issue, tried many different workarounds but no luck.....if anyone knows of a way to solve this, please let me know

**Comment by ransagy** [comment]
There aren't any. Until the author updates the build and code (or accepts the pull request doing so) it simply won't build against 0.5.x and up.

**Comment by orominioo** [comment]
> 
> 
> There aren't any. Until the author updates the build and code (or accepts the pull request doing so) it simply won't build against 0.5.x and up.

Have you work on the code or are you waiting on the author to update it?

**Comment by ransagy** [comment]
Someone else submitted a pull request to make the needed changes, it hasn't been merged (yet?).
I needed a quick solution at the time and so switched to one of the other state management solutions listed in the blazor official community page.

**Comment by torhovland** [comment]
Implemented in #12.
