### ISSUE TITLE
Linker error when adding package to project.

### ISSUE THREAD

**Issue by CDMayberry** [torhovland/blazor-redux#5]
I created a ASP.Net Core 2.1 Hosted template from VS then added the BlazorRedux package to the Client project and built it. This produced the below error. The sdk version is "2.1.300-preview2-008533" and all blazor packages are on 0.2.0

> Error	MSB3073	The command "dotnet "C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0\targets\../tools/illink/illink.dll" -c link -u link -t --verbose  -d "C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0\targets\../tools/mono/bcl/" -d "C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0\targets\../tools/mono/bcl/Facades/" -o "C:\Users\cmayberry\source\repos\BlazorTest2\BlazorTest2\BlazorTest2.Client\obj\Debug\netstandard2.0\blazor/linker/" -x "C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0\targets\BuiltInBclLinkerDescriptor.xml" -x "C:\Users\cmayberry\source\repos\BlazorTest2\BlazorTest2\BlazorTest2.Client\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\cmayberry\.nuget\packages\blazor-redux\0.0.3\lib\netstandard2.0\BlazorRedux.dll" -a "C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor\0.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor.browser\0.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.Browser.dll" -a "C:\Users\cmayberry\.nuget\packages\microsoft.extensions.dependencyinjection\2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\cmayberry\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.0.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\cmayberry\source\repos\BlazorTest2\BlazorTest2\BlazorTest2.Shared\bin\Debug\netstandard2.0\BlazorTest2.Shared.dll" -a "C:\Users\cmayberry\source\repos\BlazorTest2\BlazorTest2\BlazorTest2.Client\obj\Debug\netstandard2.0\BlazorTest2.Client.dll"" exited with code 1.	BlazorTest2.Client	C:\Users\cmayberry\.nuget\packages\microsoft.aspnetcore.blazor.build\0.2.0\targets\Blazor.MonoRuntime.targets	435

**Comment by panesofglass** [comment]
I got the same here: https://github.com/panesofglass/trail/pull/12. Probably just needs an updated release.

**Comment by torhovland** [comment]
OK, let me take a look.

**Comment by torhovland** [comment]
All right, I have released v0.0.4, which fixes this. Thanks for reporting the issue.
